### Rider http test files to manually test the API post/get

### POST: Save a new person
POST https://localhost:44416/api/person
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Doe"
}

> {% client.global.set("personId", response.body.id) %}

### GET: Retrieve the person by id
GET https://localhost:44416/api/person/{{personId}}

### Get all people
GET https://localhost:44416/api/person